# Generated by Django 5.2.5 on 2025-12-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Website URL for automation', max_length=500)),
                ('email', models.EmailField(blank=True, help_text='Login email', max_length=254, null=True)),
                ('password', models.CharField(help_text='Login password', max_length=500)),
                ('username', models.CharField(blank=True, help_text='Login username', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
