# Generated by Django 5.2.5 on 2025-12-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlinkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='credential',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
